/**
 * Ravimoshark Contract API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@ravimoshark.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type Deleted = "ACTIVE" | "DELETED" | "ALL";

export const Deleted = {
    ACTIVE: "ACTIVE" as Deleted,
    ALL: "ALL" as Deleted,
    DELETED: "DELETED" as Deleted
};
